### ISSUE TITLE
Error caught building frontend

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-admin#1116]
```
ken@192 dubbo-admin-ui % yarn build                                   
yarn run v1.22.19
$ vue-cli-service build
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '@vue/cli-plugin-unit-jest'
Require stack:
- /dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/lib/Service.js
- /dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at idToPlugin (/dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/lib/Service.js:145:14)
    at /dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/lib/Service.js:184:20
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/lib/Service.js:170:10)
    at new Service (/dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/lib/Service.js:32:25)
    at Object.<anonymous> (/dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/bin/vue-cli-service.js:15:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/lib/Service.js',
    '/dubbo-admin/dubbo-admin-ui/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by chickenlj** [comment]
I forgot to run `yarn` after updating the latest commit.
