### ISSUE TITLE
publish nacos metadata failed

### ISSUE THREAD

**Issue by jzcccc** [apache/dubbo-admin#1240]
dubbo-admin version:0.7.0
dubbo version:3.2.2
nacos version: 2.1.0

dubbo-admin config
```
admin.registry.address=nacos://127.0.0.1:8848/?namespace=dubbo&group=DEFAULT_GROUP&username=nacos&password=nacos&registry-type=service
admin.config-center=nacos://127.0.0.1:8848/?namespace=dubbo&group=DEFAULT_GROUP&username=nacos&password=nacos
admin.metadata-report.address=nacos://127.0.0.1:8848/?namespace=dubbo&group=DEFAULT_GROUP&username=nacos&password=nacos
```
nacos console:
![图片](https://github.com/apache/dubbo-admin/assets/26700791/8de5cdeb-280d-4f10-a2f7-e89cf3924d96)

dubbo-admin:
![图片](https://github.com/apache/dubbo-admin/assets/26700791/4106ec78-b4d4-44e9-bbb9-1c770ab995cd)

excetion :
```
2023-10-18 18:04:39.198  INFO 20319 --- [eduler-thread-5] org.apache.dubbo.config.ServiceConfig    :  [DUBBO] Try to register interface application mapping for service org.apache.dubbo.mock.api.MockService, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.218  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 1. Next retry delay: 68. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.311  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 2. Next retry delay: 48. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.381  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 3. Next retry delay: 19. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.423  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 4. Next retry delay: 34. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.477  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 5. Next retry delay: 42. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.543  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 6. Next retry delay: 1. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.564  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 7. Next retry delay: 12. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.618  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 8. Next retry delay: 29. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.826  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 9. Next retry delay: 99. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:39.832  WARN 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Received address refresh retry event, 1697623469826, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
2023-10-18 18:04:39.832  WARN 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Retrying address notification..., dubbo version: 3.2.5, current host: 172.26.13.121, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
2023-10-18 18:04:39.832  WARN 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Received address refresh retry event, 1697623469826, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
2023-10-18 18:04:39.832  WARN 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Retrying address notification..., dubbo version: 3.2.5, current host: 172.26.13.121, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
2023-10-18 18:04:40.020  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 10. Next retry delay: 15. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:40.220  INFO 20319 --- [eduler-thread-5] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] Failed to publish service name mapping to metadata center by cas operation. Times: 11. Next retry delay: 23. Service Interface: org.apache.dubbo.mock.api.MockService. Origin Content: null. Ticket: 0. Excepted context: dubbo-admin, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:40.244 ERROR 20319 --- [eduler-thread-5] org.apache.dubbo.config.ServiceConfig    :  [DUBBO] Failed register interface application mapping for service org.apache.dubbo.mock.api.MockService, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 5-10. This may be caused by configuration server disconnected, go to https://dubbo.apache.org/faq/5/10 to find instructions.
2023-10-18 18:04:41.996  INFO 20319 --- [yTimer-thread-1] stractMetadataReport$MetadataReportRetry :  [DUBBO] start to retry task for metadata report. retry times:75, dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:41.997  INFO 20319 --- [Report-thread-1] o.a.d.m.store.nacos.NacosMetadataReport  :  [DUBBO] store provider metadata. Identifier : org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@380d5879; definition: FullServiceDefinition{parameters={release=3.2.5, application=dubbo-admin, pid=20319, dubbo=2.0.2, anyhost=true, side=provider, interface=org.apache.dubbo.mock.api.MockService, executor-management-mode=isolation, file-cache=true, methods=mock, logger=slf4j, deprecated=false, qos.port=32222, service-name-mapping=true, generic=false, bind.port=20881, revision=3.0.0, bind.ip=172.26.13.121, prefer.serialization=fastjson2,hessian2, background=false, dynamic=true, timestamp=1697623258321}} ServiceDefinition [canonicalName=org.apache.dubbo.mock.api.MockService, codeSource=jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/, methods=[MethodDefinition [name=mock, parameterTypes=[org.apache.dubbo.mock.api.MockContext], returnType=org.apache.dubbo.mock.api.MockResult]]], dubbo version: 3.2.5, current host: 172.26.13.121
2023-10-18 18:04:42.022 ERROR 20319 --- [Report-thread-1] o.a.d.m.store.nacos.NacosMetadataReport  :  [DUBBO] Failed to put org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@380d5879 to nacos {"annotations":[],"canonicalName":"org.apache.dubbo.mock.api.MockService","codeSource":"jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/","methods":[{"annotations":[],"name":"mock","parameterTypes":["org.apache.dubbo.mock.api.MockContext"],"parameters":[],"returnType":"org.apache.dubbo.mock.api.MockResult"}],"parameters":{"release":"3.2.5","application":"dubbo-admin","pid":"20319","dubbo":"2.0.2","anyhost":"true","side":"provider","interface":"org.apache.dubbo.mock.api.MockService","executor-management-mode":"isolation","file-cache":"true","methods":"mock","logger":"slf4j","deprecated":"false","qos.port":"32222","service-name-mapping":"true","generic":"false","bind.port":"20881","revision":"3.0.0","bind.ip":"172.26.13.121","prefer.serialization":"fastjson2,hessian2","background":"false","dynamic":"true","timestamp":"1697623258321"},"types":[{"enums":[],"items":[],"properties":{"methodName":"java.lang.String","arguments":"java.lang.Object[]","serviceName":"java.lang.String"},"type":"org.apache.dubbo.mock.api.MockContext"},{"enums":[],"items":[],"properties":{},"type":"boolean"},{"enums":[],"items":["java.lang.Object"],"properties":{},"type":"java.lang.Object[]"},{"enums":[],"items":[],"properties":{},"type":"java.lang.Object"},{"enums":[],"items":[],"properties":{},"type":"java.lang.String"},{"enums":[],"items":[],"properties":{"enable":"boolean","content":"java.lang.String"},"type":"org.apache.dubbo.mock.api.MockResult"}],"uniqueId":"org.apache.dubbo.mock.api.MockService@jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/"}, cause: publish nacos metadata failed, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 1-37. This may be caused by , go to https://dubbo.apache.org/faq/1/37 to find instructions.

java.lang.RuntimeException: publish nacos metadata failed
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:387) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreProviderMetadata(NacosMetadataReport.java:224) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadataTask$1(AbstractMetadataReport.java:293) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:90) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeProviderMetadataTask(AbstractMetadataReport.java:283) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadata$0(AbstractMetadataReport.java:276) ~[dubbo-3.2.5.jar!/:3.2.5]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-10-18 18:04:42.023 ERROR 20319 --- [Report-thread-1] o.a.d.m.store.nacos.NacosMetadataReport  :  [DUBBO] Failed to put provider metadata org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@380d5879 in  FullServiceDefinition{parameters={release=3.2.5, application=dubbo-admin, pid=20319, dubbo=2.0.2, anyhost=true, side=provider, interface=org.apache.dubbo.mock.api.MockService, executor-management-mode=isolation, file-cache=true, methods=mock, logger=slf4j, deprecated=false, qos.port=32222, service-name-mapping=true, generic=false, bind.port=20881, revision=3.0.0, bind.ip=172.26.13.121, prefer.serialization=fastjson2,hessian2, background=false, dynamic=true, timestamp=1697623258321}} ServiceDefinition [canonicalName=org.apache.dubbo.mock.api.MockService, codeSource=jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/, methods=[MethodDefinition [name=mock, parameterTypes=[org.apache.dubbo.mock.api.MockContext], returnType=org.apache.dubbo.mock.api.MockResult]]], cause: Failed to put org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@380d5879 to nacos {"annotations":[],"canonicalName":"org.apache.dubbo.mock.api.MockService","codeSource":"jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/","methods":[{"annotations":[],"name":"mock","parameterTypes":["org.apache.dubbo.mock.api.MockContext"],"parameters":[],"returnType":"org.apache.dubbo.mock.api.MockResult"}],"parameters":{"release":"3.2.5","application":"dubbo-admin","pid":"20319","dubbo":"2.0.2","anyhost":"true","side":"provider","interface":"org.apache.dubbo.mock.api.MockService","executor-management-mode":"isolation","file-cache":"true","methods":"mock","logger":"slf4j","deprecated":"false","qos.port":"32222","service-name-mapping":"true","generic":"false","bind.port":"20881","revision":"3.0.0","bind.ip":"172.26.13.121","prefer.serialization":"fastjson2,hessian2","background":"false","dynamic":"true","timestamp":"1697623258321"},"types":[{"enums":[],"items":[],"properties":{"methodName":"java.lang.String","arguments":"java.lang.Object[]","serviceName":"java.lang.String"},"type":"org.apache.dubbo.mock.api.MockContext"},{"enums":[],"items":[],"properties":{},"type":"boolean"},{"enums":[],"items":["java.lang.Object"],"properties":{},"type":"java.lang.Object[]"},{"enums":[],"items":[],"properties":{},"type":"java.lang.Object"},{"enums":[],"items":[],"properties":{},"type":"java.lang.String"},{"enums":[],"items":[],"properties":{"enable":"boolean","content":"java.lang.String"},"type":"org.apache.dubbo.mock.api.MockResult"}],"uniqueId":"org.apache.dubbo.mock.api.MockService@jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/"}, cause: publish nacos metadata failed, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 3-2. This may be caused by , go to https://dubbo.apache.org/faq/3/2 to find instructions.

java.lang.RuntimeException: Failed to put org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@380d5879 to nacos {"annotations":[],"canonicalName":"org.apache.dubbo.mock.api.MockService","codeSource":"jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/","methods":[{"annotations":[],"name":"mock","parameterTypes":["org.apache.dubbo.mock.api.MockContext"],"parameters":[],"returnType":"org.apache.dubbo.mock.api.MockResult"}],"parameters":{"release":"3.2.5","application":"dubbo-admin","pid":"20319","dubbo":"2.0.2","anyhost":"true","side":"provider","interface":"org.apache.dubbo.mock.api.MockService","executor-management-mode":"isolation","file-cache":"true","methods":"mock","logger":"slf4j","deprecated":"false","qos.port":"32222","service-name-mapping":"true","generic":"false","bind.port":"20881","revision":"3.0.0","bind.ip":"172.26.13.121","prefer.serialization":"fastjson2,hessian2","background":"false","dynamic":"true","timestamp":"1697623258321"},"types":[{"enums":[],"items":[],"properties":{"methodName":"java.lang.String","arguments":"java.lang.Object[]","serviceName":"java.lang.String"},"type":"org.apache.dubbo.mock.api.MockContext"},{"enums":[],"items":[],"properties":{},"type":"boolean"},{"enums":[],"items":["java.lang.Object"],"properties":{},"type":"java.lang.Object[]"},{"enums":[],"items":[],"properties":{},"type":"java.lang.Object"},{"enums":[],"items":[],"properties":{},"type":"java.lang.String"},{"enums":[],"items":[],"properties":{"enable":"boolean","content":"java.lang.String"},"type":"org.apache.dubbo.mock.api.MockResult"}],"uniqueId":"org.apache.dubbo.mock.api.MockService@jar:file:/Users/caizhijian/IdeaProjects/dubbo-admin/dubbo-admin-distribution/target/dubbo-admin-0.7.0-SNAPSHOT.jar!/BOOT-INF/lib/dubbo-mock-api-3.0.0.jar!/"}, cause: publish nacos metadata failed
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:391) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreProviderMetadata(NacosMetadataReport.java:224) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadataTask$1(AbstractMetadataReport.java:293) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:90) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeProviderMetadataTask(AbstractMetadataReport.java:283) ~[dubbo-3.2.5.jar!/:3.2.5]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeProviderMetadata$0(AbstractMetadataReport.java:276) ~[dubbo-3.2.5.jar!/:3.2.5]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.RuntimeException: publish nacos metadata failed
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:387) ~[dubbo-3.2.5.jar!/:3.2.5]
	... 8 common frames omitted

2023-10-18 18:04:42.866 ERROR 20319 --- [-retry-thread-1] o.a.d.r.client.AbstractServiceDiscovery  :  [DUBBO] Failed to get metadata for revision after 3 retries, revision=459583ae48b0e06f1da4be635f90f7c1, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions.
2023-10-18 18:04:42.866 ERROR 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] 1/1 revisions failed to get metadata from remote: 459583ae48b0e06f1da4be635f90f7c1 , dubbo version: 3.2.5, current host: 172.26.13.121, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
2023-10-18 18:04:42.866  WARN 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Address refresh try task submitted, dubbo version: 3.2.5, current host: 172.26.13.121, error code: 99-0. This may be caused by unknown error in registry module, go to https://dubbo.apache.org/faq/99/0 to find instructions.
2023-10-18 18:04:42.866 ERROR 20319 --- [-retry-thread-1] .r.c.e.l.ServiceInstancesChangedListener :  [DUBBO] Address refresh failed because of Metadata Server failure, wait for retry or new address refresh event., dubbo version: 3.2.5, current host: 172.26.13.121, error code: 1-17. This may be caused by metadata Server failure, go to https://dubbo.apache.org/faq/1/17 to find instructions.
```

**Comment by chickenlj** [comment]
Nacos server returned with false, not sure why this happened.

**Comment by jzcccc** [comment]
It's a bug in nacos

[https://github.com/alibaba/nacos/issues/8606](url)
