### ISSUE TITLE
How to config config-center info in application.properties?

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/dubbo-admin#298]
- 首先本地启动Dubbo Admin

![image](https://user-images.githubusercontent.com/11908486/52694821-e6cfd400-2fa5-11e9-822f-6a099b3edf02.png)

- 查看服务的元数据时,报以下这个错误

![image](https://user-images.githubusercontent.com/11908486/52695070-7ffeea80-2fa6-11e9-98f1-1bfd02f901a8.png)

是一定要按照下面这个配置才行吗? 那Dubbo Admin中application.properties里默认配置为什么不直接这样写

![image](https://user-images.githubusercontent.com/11908486/52695118-9c028c00-2fa6-11e9-9533-db43737ba093.png)

**Comment by nzomkxia** [comment]
你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关

**Comment by zhaixiaoxiang** [comment]
> 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关

我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0

**Comment by nzomkxia** [comment]
我试一下，稍后给你反馈

**Comment by nzomkxia** [comment]
> > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> 
> 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0

dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo

**Comment by zhaixiaoxiang** [comment]
> > > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> > 
> > 
> > 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0
> 
> dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo

我已经改成<dubbo:registry address="zookeeper://localhost:2181"/>, 不是广播模式的问题

**Comment by zhaixiaoxiang** [comment]
> > > > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> > > 
> > > 
> > > 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0
> > 
> > 
> > dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo
> 
> 我已经改成<dubbo:registry address="zookeeper://localhost:2181"/>, 不是广播模式的问题

https://github.com/apache/incubator-dubbo/issues/3462

**Comment by zhaixiaoxiang** [comment]
> > > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> > 
> > 
> > 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0
> 
> dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo

你给的demo在启动时报如下这个错误:

```
2019-02-13 16:37:17.029 ERROR 7179 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry valid="false" zookeeperProtocol="false" prefix="dubbo.registry" />
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:162) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.checkAndUpdateSubConfigs(ServiceConfig.java:270) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:328) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58) ~[dubbo-2.7.0.jar:2.7.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:886) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.apache.dubbo.demo.DubboProviderApplication.main(DubboProviderApplication.java:13) [classes/:na]
```

**Comment by nzomkxia** [comment]
> > > > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> > > 
> > > 
> > > 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0
> > 
> > 
> > dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo
> 
> 我已经改成<dubbo:registry address="zookeeper://localhost:2181"/>, 不是广播模式的问题

dubbo:registry的配置方式还是2.6的用法，Dubbo2.7中虽然兼容，但是不会把它当做元数据中心来用，因此还是看不到元数据信息。推荐的配置是
```xml
<dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
```
然后在配置中心里面配置注册中心和元数据中心的地址，如果没有这两个地址，就会报错，我给你的demo报错就是因为配置中心里面缺少这两个配置。  
**也可以在本地把三个中心的地址都配置好**:  
```xml
<dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
<dubbo:registry address="zookeeper://127.0.0.1:2181" />
<dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>  
```
这种方式也可以读取到元数据

**Comment by zhaixiaoxiang** [comment]
> > > > > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> > > > 
> > > > 
> > > > 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0
> > > 
> > > 
> > > dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo
> > 
> > 
> > 我已经改成<dubbo:registry address="zookeeper://localhost:2181"/>, 不是广播模式的问题
> 
> dubbo:registry的配置方式还是2.6的用法，Dubbo2.7中虽然兼容，但是不会把它当做元数据中心来用，因此还是看不到元数据信息。推荐的配置是
> 
> ```
> <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
> ```
> 
> 然后在配置中心里面配置注册中心和元数据中心的地址，如果没有这两个地址，就会报错，我给你的demo报错就是因为配置中心里面缺少这两个配置。
> **也可以在本地把三个中心的地址都配置好**:
> 
> ```
> <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
> <dubbo:registry address="zookeeper://127.0.0.1:2181" />
> <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>  
> ```
> 
> 这种方式也可以读取到元数据

如果三个都配置, 则zk上的目录结构如下:
[zk: localhost:2181(CONNECTED) 0] ls /dubbo
[metadata, org.apache.dubbo.demo.DemoService]
[zk: localhost:2181(CONNECTED) 1] ls /dubbo/metadata
[consumers, routers, configurators, providers, org.apache.dubbo.demo.DemoService]

但是官网上这个图上显示的zk的目录并不是上面看到的/dubbo/metadata
http://dubbo.incubator.apache.org/img/zk-configcenter.jpg, 官网上指的是/dubbo/config/...

**Comment by nzomkxia** [comment]
> > > > > > 你的服务使用的是什么版本的Dubbo？只有Dubbo2.7支持查看元数据，和Dubbo Admin中的配置无关
> > > > > 
> > > > > 
> > > > > 我运行的是官方的dubbo-demo-xml-provider , 版本是tag 2.7.0
> > > > 
> > > > 
> > > > dubbo-demo-xml-provider采用的是广播模式，并没有连接注册中心，因此元信息不会被注册上去，可以试一下这个demo: https://github.com/nzomkxia/dubbo-demo
> > > 
> > > 
> > > 我已经改成<dubbo:registry address="zookeeper://localhost:2181"/>, 不是广播模式的问题
> > 
> > 
> > dubbo:registry的配置方式还是2.6的用法，Dubbo2.7中虽然兼容，但是不会把它当做元数据中心来用，因此还是看不到元数据信息。推荐的配置是
> > ```
> > <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
> > ```
> > 然后在配置中心里面配置注册中心和元数据中心的地址，如果没有这两个地址，就会报错，我给你的demo报错就是因为配置中心里面缺少这两个配置。
> > **也可以在本地把三个中心的地址都配置好**:
> > ```
> > <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
> > <dubbo:registry address="zookeeper://127.0.0.1:2181" />
> > <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>  
> > ```
> > 这种方式也可以读取到元数据
> 
> 如果三个都配置, 则zk上的目录结构如下:
> [zk: localhost:2181(CONNECTED) 0] ls /dubbo
> [metadata, org.apache.dubbo.demo.DemoService]
> [zk: localhost:2181(CONNECTED) 1] ls /dubbo/metadata
> [consumers, routers, configurators, providers, org.apache.dubbo.demo.DemoService]
> 
> 但是官网上这个图上显示的zk的目录并不是上面看到的/dubbo/metadata
> http://dubbo.incubator.apache.org/img/zk-configcenter.jpg, 官网上指的是/dubbo/config/...

官网上这部分展示的是配置中心的信息，对应<dubbo:config-center/> `metadata`中存储的是元数据信息，对应的是<dubbo:metadata-report/>，后续会有其他的文章来阐述这三个中心

**Comment by chickenlj** [comment]
[如何简化注册中心URL](https://github.com/apache/incubator-dubbo-website/blob/asf-site/docs/zh-cn/user/demos/simplify-registry-data.md)  
[启用元数据中心](https://github.com/apache/incubator-dubbo-website/blob/asf-site/docs/zh-cn/user/demos/metadata-report.md)

**Comment by nzomkxia** [comment]
@zhaixiaoxiang 是否方便留个联系方式？

**Comment by phpip** [comment]
用了这个 demo 也是没有信息 https://github.com/nzomkxia/dubbo-demo @nzomkxia

**Comment by phpip** [comment]
解决了：
在自己的项目中将参数改为：
   <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
    <dubbo:registry address="zookeeper://127.0.0.1:2181" simplified="true"/>
    <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
