### ISSUE TITLE
redis作为注册中心，dubbo.registry.address=redis://XXXX:6379 启动报错

### ISSUE THREAD

**Issue by zxf527** [apache/dubbo-admin#350]
`Caused by: java.lang.IllegalStateException: No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name redis
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:514)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:521)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:344)
	at org.apache.dubbo.admin.config.ConfigCenter.getDynamicConfiguration(ConfigCenter.java:80)
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$e5e4772b.CGLIB$getDynamicConfiguration$1(<generated>)
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$e5e4772b$$FastClassBySpringCGLIB$$fb588c8a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$e5e4772b.getDynamicConfiguration(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)`

**Comment by kezhenxu94** [comment]
@zxf527 Dubbo Admin 目前暂不支持 Redis 作为配置中心哦

**Comment by LittleCai** [comment]
@kezhenxu94 现在Dubbo Admin只支持zookeeper吗

**Comment by JanvenZhao** [comment]
什么时间能支持啊。。。。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
