### ISSUE TITLE
元数据中心redis，jedis连接回池问题

### ISSUE THREAD

**Issue by hudandan** [apache/dubbo-admin#431]
0.2.0版本，运行操作进入服务详情页面，第九次加载不出来了！原因是jedis没有调用returnResource释放回池。
注意：jedis3.0之后returnResource将过期，注意自己的版本，调用jedis.close内部会自动判断回池
![image](https://user-images.githubusercontent.com/13570130/59760383-c3ef5c80-92c4-11e9-971f-0cfd60d45316.png)

**Comment by pinkdawn** [comment]
遇到同样问题。

` "http-nio-8080-exec-10" #42 daemon prio=5 os_prio=0 tid=0x00007f8cb1010800 nid=0x7115 waiting on condition [0x00007f8ca20e7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006a64a4108> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:590)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:441)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:362)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at org.apache.dubbo.admin.registry.metadata.impl.RedisMetaDataCollector.doGetMetaData(RedisMetaDataCollector.java:60)`

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
