### ISSUE TITLE
2.7.2的dubbo如何使用dubbo-monitor 

### ISSUE THREAD

**Issue by rongmin** [apache/dubbo-admin#484]
如题2.7.2的dubbo如何使用dubbo-monitor？我按照md文件中的说明从incubator-dubbo-ops下载打包的monitor没有org.apache.dubbo.monitor.MonitorService服务提供者，只有com.alibaba.dubbo.monitor.MonitorService，项目跑起来提示找不到org.apache.dubbo.monitor.MonitorService报错，2.7.2版本的dubbo是没有monitor了还是我没有找对地方？

`[2019-08-13 12:09:00,232][ERROR][73aefdab40dc4ea5ac34d80505adb8c1][DubboMonitor:83]  [DUBBO] Unexpected error occur at send statistic, cause: No provider available from registry 10.72.27.60:2181 for service org.apache.dubbo.monitor.MonitorService on consumer 10.72.27.167 use dubbo version 2.7.2, please check status of providers(disabled, not registered or in blacklist)., dubbo version: 2.7.2, current host: 10.72.27.167
org.apache.dubbo.rpc.RpcException: No provider available from registry 10.72.27.60:2181 for service org.apache.dubbo.monitor.MonitorService on consumer 10.72.27.167 use dubbo version 2.7.2, please check status of providers(disabled, not registered or in blacklist).
        at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:567)
        at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:85)
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:280)
        at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:245)
        at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)
        at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55)
        at org.apache.dubbo.common.bytecode.proxy9.collect(proxy9.java)
        at org.apache.dubbo.monitor.dubbo.DubboMonitor.send(DubboMonitor.java:123)`

**Comment by nzomkxia** [comment]
请参考这个sample: https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-metrics

**Comment by rongmin** [comment]
> 请参考这个sample: https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-metrics

配置了。也启动dubbo admin了， dubbo版本 2.7.2， 没法用。 这个版本还是没有太多guideline和实例。
