### ISSUE TITLE
通过 java -jar dubbo-admin-0.1.jar 根本无法启动，一直报错，请你们弄好了再发布到社区，很尴尬啊

### ISSUE THREAD

**Issue by xinweishao** [apache/dubbo-admin#511]
通过 java -jar dubbo-admin-0.1.jar 根本无法启动，一直报错 ：ception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/log4j-to-slf4j-2.11.2.jar
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:108)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:86)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:70)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/log4j-to-slf4j-2.11.2.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:254)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:239)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
        ... 4 more
Caused by: java.io.IOException: Unable to find ZIP central directory records after reading 13863 bytes
        at org.springframework.boot.loader.jar.CentralDirectoryEndRecord.<init>(CentralDirectoryEndRecord.java:65)
        at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:52)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:121)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:109)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:287)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:262)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:250)
        ... 6 more

**Comment by xinweishao** [comment]
报错的没有这个jar 但是我看了，里面包含的有此jar

**Comment by dxx123** [comment]
建议自己打包之后运行

**Comment by xinweishao** [comment]
我就是自行打包的，用java -jar  命令一直报错 ，用另一个命令就起来了



------------------ 原始邮件 ------------------
发件人: "afterDai"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 下午4:56
收件人: "apache/dubbo-admin"<dubbo-admin@noreply.github.com>; 
抄送: "风"<304518519@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [apache/dubbo-admin] 通过 java -jar dubbo-admin-0.1.jar 根本无法启动，一直报错，请你们弄好了再发布到社区，很尴尬啊 (#511)




建议自己打包之后运行

**Comment by biyuhao** [comment]
我这边本地未能复现，现在问题解决了吗，可以清空下本地 maven 相关缓存重新打包试试

**Comment by htynkn** [comment]
可能是包损坏。
我在JDK8下无法复现，同时检验[Dockerfile](https://github.com/apache/dubbo-admin/blob/develop/docker/0.1.0/Dockerfile
)编译运行0.1也是可行的。

如果问题没有解决，请新建一个issue，附上代码commit id，java版本等信息
