### ISSUE TITLE
编译报错:build server进入到TEST阶段时报错

### ISSUE THREAD

**Issue by ltjackll** [apache/dubbo-admin#576]
zookeeper开启正常,编译到server进入到TEST阶段时报错,防火墙端口也开了
详细报错如下:
 23:16:03.600 [main-SendThread(127.0.0.1:43817)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server 127.0.0.1/127.0.0.1:43817. Will not attempt to authenticate using SASL (unknown error)
23:16:03.601 [main-SendThread(127.0.0.1:43817)] INFO org.apache.zookeeper.ClientCnxn - Socket error occurred: 127.0.0.1/127.0.0.1:43817: Connection refused
23:16:03.601 [main-SendThread(127.0.0.1:43817)] DEBUG org.apache.zookeeper.ClientCnxnSocketNIO - Ignoring exception during shutdown input
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.SocketChannelImpl.shutdownInput(SocketChannelImpl.java:780)
        at sun.nio.ch.SocketAdaptor.shutdownInput(SocketAdaptor.java:399)
        at org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:198)
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1325)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1245)
23:16:03.601 [main-SendThread(127.0.0.1:43817)] DEBUG org.apache.zookeeper.ClientCnxnSocketNIO - Ignoring exception during shutdown output
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.SocketChannelImpl.shutdownOutput(SocketChannelImpl^C.java:797)
        at sun.nio.ch.SocketAdaptor.shutdownOutput(SocketAdaptor.java:407)
        at org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:205)
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1325)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1245)

**Comment by cheneybj** [comment]
尝试跳过测试类编译

**Comment by htynkn** [comment]
CI pass with whole tests, if you have issue with building in local, try skip tests
`./mvnw clean package -DskipTests`
