### ISSUE TITLE
容器运行时关于zookeeper的环境变量不生效

### ISSUE THREAD

**Issue by jackiehope** [apache/dubbo-admin#607]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7
* Registry center detail (type and version): zk
* Operating System version: CentOS7.6
* Java version: 8

### Steps to reproduce this issue

1. Dockerfile内容
```
ARG  BRANCH=develop

FROM maven:3-openjdk-8
ARG  BRANCH
COPY settings.xml /usr/share/maven/ref/
RUN mkdir /source && wget https://github.com/apache/dubbo-admin/archive/${BRANCH}.zip && unzip -q ${BRANCH}.zip -d /source
WORKDIR /source/dubbo-admin-${BRANCH}
RUN mvn -s /usr/share/maven/ref/settings.xml --batch-mode clean package -Dmaven.test.skip=true
RUN grep '<artifactId>dubbo-admin</artifactId>' pom.xml -A 1 | grep version | grep -o '>.*<' | tr -d '><' > /source/version


FROM openjdk:8-jre
ARG  BRANCH
LABEL maintainer="dev@dubbo.apache.org"
WORKDIR /opt/app
COPY --from=0 /source/version /opt/app/version
COPY --from=0 /source/dubbo-admin-${BRANCH}/dubbo-admin-distribution/target/* /opt/app/
CMD export VERSION=$(cat /opt/app/version); java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -jar /opt/app/dubbo-admin-${VERSION}.jar
EXPOSE 8080
```
2. settings.xml文件内容
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>/usr/share/maven/ref/repository</localRepository>
  <mirrors>
    <mirror>
      <id>nexus-aliyun</id>
      <name>nexus aliyun Maven Mirror Repository</name>
      <url>http://maven.aliyun.com/nexus/content/groups/public</url>
      <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
</settings>
```
3. stack.yml文件内容
```
version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  admin:
    #image: dubbo-admin:develop
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
    ports:
      - 8080
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
```

4.docker-compose启动命令
```
docker-compose -f stack.yml up
```
Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
服务应该可以正常启动，并能连接到对应的zookeeper地址，在当前示例中应该是zookeeper。

### Actual Result

What actually happens?
服务启动时报错，报错内容为连接127.0.0.1:2181错误，该地址为property文件中的默认地址，初步断定是环境变量没有被服务读取到，因为环境变量名中带`.`，所以通过env命令是查看不到的，但是我通过--build-arg BRANCH=0.2.0编译出来的镜像是可以访问到zookeeper，对java开发不熟悉，没法深入到源码层进行分析。

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by jackiehope** [comment]
报错内容
```
admin_1      | 2020-05-19 10:11:24.976 ERROR 7 --- [yTimer-thread-1] org.apache.curator.ConnectionState       : Connection timed out for connection string (127.0.0.1:2181) and timeout (5000) / elapsed (41005)
admin_1      |
admin_1      | org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
admin_1      | 	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
admin_1      | 	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
admin_1      | 	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
admin_1      | 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:740)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
admin_1      | 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
admin_1      | 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
admin_1      | 	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:95)
admin_1      | 	at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:71)
admin_1      | 	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:154)
admin_1      | 	at org.apache.dubbo.registry.retry.FailedSubscribedTask.doRetry(FailedSubscribedTask.java:44)
admin_1      | 	at org.apache.dubbo.registry.retry.AbstractRetryTask.run(AbstractRetryTask.java:124)
admin_1      | 	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)
admin_1      | 	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)
admin_1      | 	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)
admin_1      | 	at java.lang.Thread.run(Thread.java:748)
admin_1      |
admin_1      | 2020-05-19 10:11:30.978 ERROR 7 --- [yTimer-thread-1] org.apache.curator.ConnectionState       : Connection timed out for connection string (127.0.0.1:2181) and timeout (5000) / elapsed (47006)
```

**Comment by xishian** [comment]
https://hub.docker.com/r/apache/dubbo-admin
docker run -d -p 8998:8080 -e admin.registry.address=zookeeper://your_hostname:2181 \
        apache/dubbo-admin

**Comment by jackiehope** [comment]
@xishian 不好意思，issue中没有描述清楚，我用的是最新develop构建的镜像，docker上的镜像版本还是0.1,想使用最新版本。

**Comment by htynkn** [comment]
应该是docker-compose的env没有正确传入
```
services:
  env:
    entrypoint:
    - env
    environment:
      admin.registry.address: zookeeper://zookeeper:2181
    image: busybox
version: '3'
```
