### ISSUE TITLE
dubbo-admin 泛型参数测试 ClassNotFoundException

### ISSUE THREAD

**Issue by WangJi92** [apache/dubbo-admin#610]
# Environment

* Dubbo version: 2.7.0
* Registry center detail (type and version): zk
* Operating System version: Cenos
* Java version: 1.8

### Steps to reproduce this issue

1. 编写一个泛型的接口
2. dubbo-admin 进行测试
/api/dev/test
```json
{
    "service": "Dubbo/xxxx:1.0.0",
    "method": "xxxMethod",
    "parameterTypes": [
        "java.util.List<xxxx.model.dto.ConfigValueDTO>"
    ],
    "params": [
        [
            {
                "productKey": "",
                "configValue": "",
                "configType": "",
                "moduleKey": "",
                "status": ""
            }
        ]
    ]
}
```
3. result 
java.lang.ClassNotFoundException: java.util.List<xxxx.model.dto.ConfigValueDTO>

```xml
org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:135) 
at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) 
at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) 
at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) 
at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:39) 
at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) 
at com.navercorp.pinpoint.plugin.micro.service.auth.dubbo.apache.AuthProviderFilter.invoke(AuthProviderFilter.java:42) 
at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) 
at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108) 
at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:103) 
at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200) 
at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) 
at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.ClassNotFoundException: java.util.List<xxxx.model.dto.ConfigValueDTO>\n\
tat java.net.URLClassLoader.findClass(URLClassLoader.java:382) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) 
at com.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:101) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) 
at java.lang.Class.forName0(Native Method) 
at java.lang.Class.forName(Class.java:348) 
at org.apache.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:741)
 at org.apache.dubbo.common.utils.ReflectUtils.name2class(ReflectUtils.java:668)
 at org.apache.dubbo.common.utils.ReflectUtils.findMethodByMethodSignature(ReflectUtils.java:883) 
at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:62) ... 15 
```

### Expected Result
1、参考这个[泛化调用](https://dubbo.gitbooks.io/dubbo-user-book/demos/generic-reference.html),参数中有泛型的处理不对象 ，在泛化调用的时候传参和data 传递数据要特殊处理。

### Actual Result

What actually happens?
1、如果参数类型是接口，或者List等丢失泛型，可通过class属性指定类型。

**Comment by zlm0125** [comment]
指定下class

**Comment by WangJi92** [comment]
> 指定下class
这个请求参数params 按道理应该自动填写,"java.util.List<xxxx.model.dto.ConfigValueDTO> 这个类型不是用户控制的
```json
{
    "service": "Dubbo/xxxx:1.0.0",
    "method": "xxxMethod",
    "parameterTypes": [
        "java.util.List<xxxx.model.dto.ConfigValueDTO>"
    ],
    "params": [
        [
            {
                "productKey": "",
                "configValue": "",
                "configType": "",
                "moduleKey": "",
                "status": ""
            }
        ]
    ]
}
```

**Comment by WangJi92** [comment]
> 指定下class

我测试了一下，就算手动在控制台添加class 也是不行的，泛化调用 前面的参数类型 有问题 应该是java.util.List,而不是java.util.List<xxxx.model.dto.ConfigValueDTO>

**Comment by zlm0125** [comment]
> > 指定下class
> 
> 我测试了一下，就算手动在控制台添加class 也是不行的，泛化调用 前面的参数类型 有问题 应该是java.util.List,而不是java.util.List<xxxx.model.dto.ConfigValueDTO>

需要在ServiceTest这里做下处理，正常的api泛化是需要指定下class

**Comment by WangJi92** [comment]
> > > 指定下class
> > 
> > 
> > 我测试了一下，就算手动在控制台添加class 也是不行的，泛化调用 前面的参数类型 有问题 应该是java.util.List,而不是java.util.List<xxxx.model.dto.ConfigValueDTO>
> 
> 需要在ServiceTest这里做下处理，正常的api泛化是需要指定下class

是滴 需要官方支持一下子

**Comment by WangJi92** [comment]
tag:0.2 版本(最新) org.apache.dubbo.admin.service.impl.GenericServiceImpl
![image](https://user-images.githubusercontent.com/20874972/83525719-f4e99100-a517-11ea-8cca-0f417578c3f0.png)

tag:develop 好像修复泛型的信息 ，前端自动带上泛型class类信息不知道有没有？
![image](https://user-images.githubusercontent.com/20874972/83525967-4db92980-a518-11ea-886a-57150cb02228.png)
