### ISSUE TITLE
使用nacos 注册中心，升级到2.7.6 报错

### ISSUE THREAD

**Issue by Devin6Tam** [apache/dubbo-admin#618]
Caused by: java.lang.IllegalStateException: No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name nacos
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:599) ~[dubbo-common-2.7.6.jar:2.7.6]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:606) ~[dubbo-common-2.7.6.jar:2.7.6]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:405) ~[dubbo-common-2.7.6.jar:2.7.6]
	at org.apache.dubbo.admin.config.ConfigCenter.getDynamicConfiguration(ConfigCenter.java:90) ~[classes/:na]
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$44b90a9e.CGLIB$getDynamicConfiguration$1(<generated>) ~[classes/:na]
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$44b90a9e$$FastClassBySpringCGLIB$$df7e162f.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$44b90a9e.getDynamicConfiguration(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 49 common frames omitted

**Comment by zhoushaohe** [comment]
@Devin6Tam Dear davin 你在升级2.7.6之前用得什么版本， nacos 正常工作吗？

**Comment by XB0228** [comment]
很遗憾，这个问题到今天还没解决
