### ISSUE TITLE
使用Docker + Nacos 无法启动Dubbo-admin

### ISSUE THREAD

**Issue by bggmjxh** [apache/dubbo-admin#790]
yml配置文件如下：
`
  dubboadmin:
    image: apache/dubbo-admin
    depends_on:
      - nacos 
    ports:
      - 8849:8080
    environment:
      - admin.registry.address=nacos://127.0.0.1:8848?group=DEFAULT_GROUP&namespace=public
      - admin.config-center=nacos://127.0.0.1:8848?group=dubbo
      - admin.metadata-report.address=nacos://127.0.0.1:8848?group=dubbo
      - admin.registry.group=dubbo
      - admin.config-center.group=dubbo
      - admin.metadata-report.group=dubbo
      - admin.registry.namespace=public
      - admin.config-center.namespace=public
      - admin.metadata-report.namespace=public

`

容器内启动日志报错如下：
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dubbo.admin.registry.config.GovernanceConfiguration]: Factory method 'getDynamicConfiguration' threw exception; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name nacos

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)

	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)

	... 55 common frames omitted

Caused by: java.lang.IllegalStateException: No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name nacos

	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:514)

	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:521)

	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:344)

	at org.apache.dubbo.admin.config.ConfigCenter.getDynamicConfiguration(ConfigCenter.java:82)

	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$44c88926.CGLIB$getDynamicConfiguration$1(<generated>)

	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$44c88926$$FastClassBySpringCGLIB$$e127e315.invoke(<generated>)

	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)

	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)

	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$44c88926.getDynamicConfiguration(<generated>)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

	... 56 common frames omitted

`

**Comment by bggmjxh** [comment]
nacos已经配置并启动。

**Comment by xingpengcheng417** [comment]
> nacos已经配置并启动。

能把配置发一下吗
