### ISSUE TITLE
看其他的issues修改的配置，后台还是看不到服务元数据

### ISSUE THREAD

**Issue by Mxgxg** [apache/dubbo-admin#816]
dubbo-admin:0.3.0，拉取今天的develop分支的代码
dubbo:2.7.12
看其他的issues修改的配置，配置的两天，后台还是看不到服务元数据。
还是哪里配置有问题吗？
![8f92dc53d83d64a2181a076d34f5943](https://user-images.githubusercontent.com/79822553/132331928-c2c90efe-f34e-4c90-917d-30127079b32a.png)
![37193f999378ac662b2aac078ff3083](https://user-images.githubusercontent.com/79822553/132331940-6329a300-5f94-4479-8b94-d54fe3816c30.png)
![916c54fc9f5cd2c4ef31c5f12700d77](https://user-images.githubusercontent.com/79822553/132331954-0c203b81-b800-483f-bd07-efe0a9e7e09f.png)
![fbfe48f6e661d278409539868ee302f](https://user-images.githubusercontent.com/79822553/132331970-859659fb-1770-4ef5-ae16-78f248aa8859.png)
![97fa1417db88c7ba1fd1cbd5045a3cf](https://user-images.githubusercontent.com/79822553/132331981-a8b6c7a9-3923-4d79-94e5-170f8aa0e56b.png)

**Comment by haoyann** [comment]
在 dubbo-admin 应该配置 `admin.config-center` 的地址，这样才能读取 `dubbo.properties` 的内容。

**Comment by Mxgxg** [comment]
> 在 dubbo-admin 应该配置`admin.config-center`的地址，这样才能读取`dubbo.properties`的内容。

**Comment by Mxgxg** [comment]
> 在 dubbo-admin 应该配置`admin.config-center`的地址，这样才能读取`dubbo.properties`的内容。
添加配置admin.config-center
![75a9ef7e90ebd4098ea6503a27c8762](https://user-images.githubusercontent.com/79822553/132444051-24a54f02-f6f4-436d-8d77-4f25f9b52d3d.png)
还是没有，您帮我确认下admin-registry.address的分组属性需要和nacos上的元数据的分组对应吗

**Comment by haoyann** [comment]
`admin-registry.address` 需要对应注册中心的分组，配置中心和元数据中心如果 namespace 是 public 不需要填写。

**Comment by Mxgxg** [comment]
> `admin-registry.address` 需要对应中心的成就，配置中心和元数据中心如果命名空间是公共的，则无需填写。


您有交流群吗？这边有问题交流比较麻烦

**Comment by Mxgxg** [comment]
> `admin-registry.address` 需要对应注册中心的分组，配置中心和元数据中心如果 namespace 是 public 不需要填写。


编译develop报错,连接不上nacos,获取不到所有服务
ERROR [main] (FailbackRegistry.java:317) -  [DUBBO] Failed to subscribe admin://192.168.91.1?category=providers,consumers,routers,configurators&check=false&classifier=*&enabled=*&group=*&interface=*&version=*, waiting for retry, cause: Failed to get all serviceName from nacos, url: nacos://10.20.60.114:8848/org.apache.dubbo.registry.RegistryService?group=dubbo&interface=org.apache.dubbo.registry.RegistryService&namespace=public&password=nacos&username=nacos, cause: Request nacos server failed: , dubbo version: 3.0.2.1, current host: 192.168.91.1
org.apache.dubbo.rpc.RpcException: Failed to get all serviceName from nacos, url: nacos://10.20.60.114:8848/org.apache.dubbo.registry.RegistryService?group=dubbo&interface=org.apache.dubbo.registry.RegistryService&namespace=public&password=nacos&username=nacos, cause: Request nacos server failed: 
	at org.apache.dubbo.registry.nacos.NacosRegistry.getAllServiceNames(NacosRegistry.java:407)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNamesForOps(NacosRegistry.java:375)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames(NacosRegistry.java:277)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:193)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:298)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:106)
	at org.apache.dubbo.admin.service.RegistryServerSync.startSubscribe(RegistryServerSync.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:108)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at org.apache.dubbo.admin.DubboAdminApplication.main(DubboAdminApplication.java:31)
Caused by: ErrCode:500, ErrMsg:Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:227)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.getServiceList(NamingGrpcClientProxy.java:175)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.getServiceList(NamingClientProxyDelegate.java:137)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:440)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:428)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.getServicesOfServer(NacosNamingServiceWrapper.java:70)
	at org.apache.dubbo.registry.nacos.NacosRegistry.getAllServiceNames(NacosRegistry.java:384)
	... 24 more
Caused by: ErrCode:-401, ErrMsg:Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:656)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:636)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:217)
	... 30 more



同样的配置，编译master就可以看到后台服务了。

**Comment by haoyann** [comment]
Nacos 用的什么版本。

**Comment by Mxgxg** [comment]
> Nacos 用的什么版本。

1.4.1的

**Comment by haoyann** [comment]
你把 admin 的 `nacos-client` 改为使用 1.4.1 版本，现在使用的是2.x 版本有些方法与 1.4.x 不兼容。

**Comment by Mxgxg** [comment]
> 你把 admin 的 `nacos-client` 改为使用 1.4.1 版本，现在使用的是2.x 版本有些方法与 1.4.x 不兼容。

修改之后又出现以下问题了，回去寻找其他的服务的元数据，其他服务的元数据都没注册上去呢，不知道是不是dubbo版本的问题，我用的是2.7.12，我想过修改版本，可是编译不通过了
![1](https://user-images.githubusercontent.com/79822553/132670149-b83f13cc-05eb-4c94-aa62-bca904a6a138.png)


然后发现一个小BUG，在修改动态配置时，前台页面接收版本号变量名与后台接收不一致，不能添加、修改版本号
![2](https://user-images.githubusercontent.com/79822553/132670371-2632763a-e845-4440-b42d-124d4686eeb9.png)
![3](https://user-images.githubusercontent.com/79822553/132670386-bccc15e6-c664-4094-815d-1b94e918665a.png)

**Comment by haoyann** [comment]
你用的 `spring-cloud-dubbo` 吗，现在并不支持。

**Comment by Mxgxg** [comment]
> 你用的 `spring-cloud-dubbo` 吗，现在并不支持。


好的 知道了，谢谢您的解答。
