### ISSUE TITLE
服务统计该怎么使用?

### ISSUE THREAD

**Issue by trdmm** [apache/dubbo-admin#860]
第一次用 Dubbo, 应该怎么配置呀 😭 
**SpringBoot:** 2.5.6
**Dubbo:** 3.0.4
**Dubbo-Admin:** 0.4.0
***
**Provider** 已引入依赖:
```xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-monitor-default</artifactId>
    <version>3.0.4</version>
</dependency>
```
使用的多协议( dubbo+grpc ), application.yml:
```yaml
dubbo:
  scan:
    base-packages:
      - org.zjxy.dubbo.server.service.impl
  application:
    name: Dubbo-Server-BoloBolo
  registry:
    client: curator
    address: zookeeper://192.168.56.1:2181
    parameters:
      registry-type: service
  config-center:
    address: zookeeper://192.168.56.1:2181
  metadata-report:
    address: zookeeper://192.168.56.1:2181
  protocols:
    dubbo:
      name: dubbo
      port: 9096
    grpc:
      name: grpc
      port: 9097
```
关于**Metrics**的不知道怎么配了:
1. 如果这样
```yaml
dubbo:
  metricses:
    dubbo:
      protocol: dubbo
      port: 9096
    grpc:
      protocol: grpc
      port: 9097
```
启动时提示这个错误:
```
java.lang.IllegalStateException: load config failed, id: grpc, type:MetricsConfig
	at org.apache.dubbo.config.context.AbstractConfigManager.lambda$loadConfigsOfTypeFromProps$7(AbstractConfigManager.java:486) ~[dubbo-3.0.4.jar:3.0.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.apache.dubbo.config.context.AbstractConfigManager.loadConfigsOfTypeFromProps(AbstractConfigManager.java:462) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.context.ConfigManager.loadConfigs(ConfigManager.java:241) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.loadApplicationConfigs(DefaultApplicationDeployer.java:227) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:197) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:419) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:68) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:55) ~[dubbo-3.0.4.jar:3.0.4]
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:34) ~[dubbo-3.0.4.jar:3.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:881) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:580) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.zjxy.dubbo.server.DubboServerApp.main(DubboServerApp.java:18) ~[classes/:na]
```

2. 如果去掉 grpc 的,
```yaml
dubbo:
  metricses:
    dubbo:
      protocol: dubbo
      port: 9096
###########或者#########
dubbo:
  metrics:
     protocol: dubbo
     port: 9096
```
在 **dubbo-admin** 中提示:
```
System Error, please try again later! Message:Found multiple ReferenceConfigs with unique service name [org.apache.dubbo.monitor.MetricsService], 
previous: <dubbo:reference sticky="false" url="dubbo://192.168.20.36:9096?scope=remote&cache=true" interface="org.apache.dubbo.monitor.MetricsService" />,
 later: <dubbo:reference url="dubbo://192.168.20.36:9096?scope=remote&cache=true" interface="org.apache.dubbo.monitor.MetricsService" />. 
There can only be one instance of ReferenceConfig with the same triple (group, interface, version).
 If multiple instances are required for the same interface, please use a different group or version.
```

另外, 应用内还需要配置什么吗 ❓

**Comment by haoyann** [comment]
应该和这个问题是一样的[#9338](https://github.com/apache/dubbo/issues/9338)。

**Comment by skx001** [comment]
同问，请问怎么配置的

**Comment by habertzk** [comment]
> 同问，请问怎么配置的
hi，我最近也遇到这个问题了，请问你现在解决了吗？

**Comment by habertzk** [comment]
> 同问，请问怎么配置的

hi，我最近也遇到这个问题了，请问你现在解决了吗？

**Comment by skx001** [comment]
> 

https://mp.csdn.net/mp_blog/creation/editor/123279888看下这个

**Comment by habertzk** [comment]
> > 
> 
> 看下这个 https://mp.csdn.net/mp_blog/creation/editor/123279888

链接错了吗？打开是个新的编辑页面。

**Comment by skx001** [comment]
> > > 
> > 
> > 
> > 看下这个 https://mp.csdn.net/mp_blog/creation/editor/123279888
> 
> 链接错了吗？打开是个新的编辑页面。
试试这个
https://blog.csdn.net/qq_29316891/article/details/123279888

**Comment by habertzk** [comment]
> > > >
> > 
> > 
> > 链接错了吗？打开是个新的编辑页面。
> > 试试这个
> > https://blog.csdn.net/qq_29316891/article/details/123279888
我看了下，我的dubbo版本是3.0.5，配置和你的一样，dubbo admin 服务统计页面出现了和https://github.com/apache/dubbo/issues/9338一样的问题，你试过3.0以上的版本可以正常使用吗？还有个问题，你提供的dubbo admin 后台是你自己修复后的版本吗？

**Comment by skx001** [comment]
> 

3.0以上的版本我试过，不行，那个dubbo-admin是我修复过的版本

**Comment by habertzk** [comment]
> > 
> 
> 3.0以上的版本我试过，不行，那个dubbo-admin是我修复过的版本

好的，谢谢。

**Comment by Leme34** [comment]
我用的Dubbo是2.7.18，对应最高可用dubbo-amin版本为0.3.0，摸着源码自己改好了，有完整的本地运行demo，供大家参考，详见https://github.com/Leme34/dubbo-spi-demo/tree/master/dubbo-admin
![1708596086266](https://github.com/apache/dubbo-admin/assets/32232194/199be851-f429-4f1c-8808-c0776a159de3)
