### ISSUE TITLE
dubbo -admin 无法注册到nacos

### ISSUE THREAD

**Issue by wolfewf** [apache/dubbo-admin#867]
- [ ] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 0.4.0
* Java version: 1.8.0_301
* nacos server version: 2.0.3

### Steps to reproduce this issue

1. dubbo-admin-server模块使用的nacos-client版本是2.0.2，启动时无法注册到nacos，把nacos-client版本升级到2.0.3还是没办法注册，改成1.4.2版本就可以成功注册上去

**Comment by haoyann** [comment]
你是说将 `dubbo-admin` 注册到 nacos 吗？我本地测试无论是 `dubbo-admin` 本身注册到 nacos 还是 `dubbo-admin` 监听 nacos 上的服务都是可以的。检查一下是否有错误日志呢?

**Comment by wolfewf** [comment]
错误日志就是nacos无法连接，换了nacos-client版本就可以了

**Comment by bbenguo** [comment]
nacos开启用户名密码验证后就连不上了，提示认证失败

**Comment by bbenguo** [comment]
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:227) ~[nacos-client-2.0.2.jar!/:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:116) ~[nacos-client-2.0.2.jar!/:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.2.jar!/:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.2.jar!/:na]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:57) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:170) ~[dubbo-3.0.2.1.jar!/:3.0.2.1]
	... 45 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: authorization failed!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:219) ~[nacos-client-2.0.2.jar!/:na]
	... 50 common frames omitted
