### ISSUE TITLE
启动服务消费者出现异常java.nio.channels.OverlappingFileLockException: null

### ISSUE THREAD

**Issue by startjava** [apache/dubbo-admin#875]
2022-02-24 17:33:28.417  INFO 20832 --- [           main] o.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Notify urls for subscribe url dubbo://192.168.56.1/com.ghy.www.api.IService1?application=my-zookeeper-consumer&background=false&category=providers,configurators,routers&dubbo=2.0.2&interface=com.ghy.www.api.IService1&logger=slf4j&metadata-type=remote&methods=getHello&pid=20832&qos.enable=false&release=3.0.5&side=consumer&sticky=false&timestamp=1645695208396, url size: 3, dubbo version: 3.0.5, current host: 192.168.56.1
2022-02-24 17:33:28.418  WARN 20832 --- [           main] o.a.d.r.integration.RegistryDirectory    :  [DUBBO] Servicecom.ghy.www.api.IService1 received empty address list with no EMPTY protocol set, trigger empty protection., dubbo version: 3.0.5, current host: 192.168.56.1
2022-02-24 17:33:28.427  WARN 20832 --- [andler-thread-1] o.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Failed to save registry cache file, will retry, cause: null, dubbo version: 3.0.5, current host: 192.168.56.1

java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[na:1.8.0_321]
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[na:1.8.0_321]
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107) ~[na:1.8.0_321]
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155) ~[na:1.8.0_321]
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:555) [dubbo-3.0.5.jar:3.0.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_321]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_321]

2022-02-24 17:33:28.427  WARN 20832 --- [andler-thread-2] o.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Failed to save registry cache file, will retry, cause: null, dubbo version: 3.0.5, current host: 192.168.56.1

java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[na:1.8.0_321]
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[na:1.8.0_321]
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107) ~[na:1.8.0_321]
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155) ~[na:1.8.0_321]
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:555) [dubbo-3.0.5.jar:3.0.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_321]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_321]

2022-02-24 17:33:28.428  INFO 20832 --- [           main] o.a.d.r.c.m.MetadataServiceNameMapping   :  [DUBBO] com.ghy.www.api.IService1 mapping to [my-zookeeper-provider] instructed by remote metadata center., dubbo version: 3.0.5, current host: 192.168.56.1

**Comment by startjava** [comment]
使用dubbo-admin 0.4.0版本
<spring-boot.version>2.6.3</spring-boot.version>
        <dubbo.version>3.0.5</dubbo.version>
