### ISSUE TITLE
please check whether related SPI module is missing

### ISSUE THREAD

**Issue by hujwGitHub2017** [apache/dubbo-admin#897]
- [ ] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x ] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 0.4.0
* Registry center detail (type and version):
* Operating System version:7.5
* Java version: 1.8

### Steps to reproduce this issue

Pls. provide [GitHub address] to reproduce this issue.

https://github.com/apache/dubbo-admin.git

What actually happens?

If there is an exception, please attach the exception trace:

java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name dubbo, no related exception was found, please check whether related SPI module is missing.
        at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:688)
        at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:695)
        at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:495)
        at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:475)
        at org.apache.dubbo.registry.client.DefaultServiceDiscoveryFactory.createDiscovery(DefaultServiceDiscoveryFactory.java:46)
        at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:45)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:45)
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:141)
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:119)
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:104)
        at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
        at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:159)
        at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:34)
        at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
        at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:359)
        at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:214)
        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
Just put your stack trace here!
```

**Comment by haoyann** [comment]
看看 `admin.registry.address` 配置的是什么呢？

**Comment by zhrgithub** [comment]
你猜啊
